config/routes.rb
get 'email_logs', :to => 'email_logs#index'
get 'email_logs/:object_type/:object_id', :to => 'email_logs#show', :as => :object_email_logs

get 'email_tracker/:image.:format', :to => 'email_tracker#index', :image => '1x1', :format => 'png', :as => :email_tracker

app/controllers/email_logs_controller.rb
class EmailLogsController < ApplicationController
    layout 'admin'
    self.main_menu = false if self.respond_to?(:main_menu)

    before_action :require_admin
    before_action :find_notifiable, :only => :show

    def index
        scope = Maillog.all
        if params[:from].present?
            begin; @from = params[:from].to_date; rescue; end
            scope = scope.where("#{Maillog.table_name}.date > ?", @from) if @from
        end
        if params[:to].present?
            begin; @to = params[:to].to_date + 1; rescue; end
            scope = scope.where("#{Maillog.table_name}.date < ?", @to) if @to
        end
        scope = scope.like(params[:q]) if params[:q].present?
        @maillog_count = scope.count
        @maillog_pages = Paginator.new(@maillog_count, per_page_option, params[:page])
        @maillogs = scope.preload(:address_fields => :address).order(:id => :desc).limit(@maillog_pages.per_page).offset(@maillog_pages.offset).to_a
        @user_addresses_map = load_addresses_map
    end

    def show
        addresses = @maillogs.collect{ |maillog| maillog.recipients }.flatten.uniq
        @recipients = User.active.having_mail(addresses).to_a
        if request.xhr?
            render :layout => false
        else
            redirect_to email_logs_path(:q => "redmine.#{@notifiable.class.name.demodulize.underscore}-#{@notifiable.id}.")
        end
    end

private

    def load_addresses_map
        addresses = @maillogs.collect{ |maillog| maillog.addresses }.flatten.uniq
        map = EmailAddress.select(:user_id, :address)
                          .where("LOWER(address) IN (?)", addresses.map{ |address| address.downcase })
                          .inject({}) do |hash, record|
            hash[record.address.downcase] = record.user_id
            hash
        end
        users = User.active.where(:id => map.values.uniq).inject({}) do |hash, user|
            hash[user.id] = user
            hash
        end
        map.transform_values{ |user_id| users[user_id] }.compact
    end

    def find_notifiable
        klass       = Object.const_get(params[:object_type].camelcase)
        @notifiable = klass.find(params[:object_id])
        @maillogs   = Maillog.where(:notifiable => @notifiable).to_a
        render_404 unless @maillogs.any?
    rescue NameError, ActiveRecord::RecordNotFound
        render_404
    end

end

app/helpers/email_logs_helper.rb
module EmailLogsHelper

    def render_email_addresses(addresses, with_emails = false)
        addresses.collect{ |address|
            address_key = address.downcase
            if @user_addresses_map[address_key]
                user_link = link_to_user(@user_addresses_map[address_key])
                with_emails ? content_tag('span', "#{user_link} &lt;#{address}&gt;".html_safe, :class => 'address') : user_link
            else
                content_tag('span', address, :class => 'address')
            end
        }.join(', ').html_safe
    end

    def render_subject(maillog)
        subject = h(maillog.subject)
        subject.sub!(/(?<=\A\[|\ARe: \[)#{Regexp.escape(h(maillog.project.name))}(?= -|\])/) do
            link_to_project(maillog.project)
        end if maillog.project
        notifiable = maillog.notifiable rescue nil
        notifiable = notifiable.issue if notifiable.is_a?(Journal)
        if notifiable.is_a?(Issue)
            subject.sub!(/(?<=- )#{Regexp.escape(h("#{notifiable.tracker} ##{notifiable.id}"))}(?=\])/) do
                link_to_issue(notifiable, :subject => false)
            end
        elsif notifiable.is_a?(Message)
            subject.sub!(/(?<=- )#{Regexp.escape(h(notifiable.board.name))} - msg#{notifiable.root.id}(?=\])/) do
                link_to(notifiable.board.name, project_board_path(notifiable.board.project, notifiable.board)) + ' - ' +
                link_to("msg#{notifiable.root.id}", board_message_path(notifiable.board_id, notifiable.parent_id || notifiable.id, {
                    :anchor => (notifiable.parent_id ? "message-#{notifiable.id}" : nil),
                    :r      => (notifiable.parent_id && notifiable.id)
                }))
            end
        end
        subject.html_safe
    end

    def render_maillog_links(maillogs)
        maillogs.sort.uniq(&:message_id).collect{ |maillog|
            message_id = maillog.opened? ? content_tag('span', maillog.message_id, :class => 'icon icon-checkmark') : maillog.message_id
            link_to(message_id, email_logs_path(:q => maillog.message_id), :class => 'email-log-link', :target => '_blank')
        }.join(',<br />').html_safe
    end

    def render_notifiable(maillog)
        method_name = "link_to_#{maillog.notifiable_type.underscore}".to_sym
        if respond_to?(method_name)
            send(method_name, maillog.notifiable)
        else
            "#{maillog.notifiable_type}##{maillog.notifiable_id}"
        end
    rescue
        content_tag('span', "#{maillog.notifiable_type}##{maillog.notifiable_id}", :class => 'notifiable-error')
    end

    def link_to_journal(journal, options = {})
        link_to("#{journal.issue.tracker} ##{journal.issue.id}", issue_path(journal.issue, :anchor => "change-#{journal.id}"),
                :class => journal.issue.css_classes) + ': ' + journal.issue.subject
    end

    def link_to_news(news)
        link_to(news.title, news_path(news))
    end

    def link_to_comment(comment)
        link_to(comment.commented.title, news_path(comment.commented, :anchor => 'comments'))
    end

    def link_to_wiki_content(wiki)
        link_to(wiki.page.pretty_title, url_for(:controller => 'wiki', :action => 'show', :project_id => wiki.project, :id => wiki.page.title))
    end

end

app/views/email_logs/_issues.html.erb
<% maillogs = @issue ? Maillog.where(:notifiable => @issue).to_a : [] %>
<% if maillogs.present? %>
  <%= javascript_tag do %>
    var $contextual = $('#content > .contextual').first();
    var $target = $contextual.find('.drdn .drdn-items');
    if ($target.length == 0) {
        $target = $contextual;
    }
    $('<a>', {
      'class': 'icon icon-email-log<%= ' opened' if maillogs.any?{ |maillog| maillog.opened? } %>',
      href: '<%= escape_javascript(raw(email_logs_path(:q => "redmine.issue-#{@issue.id}."))) %>',
      text: '<%= escape_javascript(l(:label_email_log)) %>',
      click: function() {
        $(this).closest('.drdn').removeClass('expanded');
        var $emailLog = $('#issue-<%= @issue.id %>-email-log');
        if ($emailLog.length > 0) {
          $emailLog.toggle();
        } else {
          $.ajax({
            url: '<%= escape_javascript(raw(object_email_logs_path(:object_type => 'issue', :object_id => @issue.id))) %>',
            success: function(data) {
              $('#content > div.issue').before(data);
            }
          });
        }
        return false;
      }
    }).appendTo($target);
  <% end %>
<% end %>

<% @journals = @comments if @journals.blank? && @comments.present? %>
<% if @journals.present? %>
  <% maillogs = Maillog.where(:notifiable => @journals).to_a %>
  <% if maillogs.present? %>
    <%= javascript_tag do %>
      var logs_path = '<%= escape_javascript(raw(email_logs_path)) %>';
      var link_label = '<%= escape_javascript(l(:label_email_log)) %>';
      var options = { a_common_libs: <%= Redmine::Plugin.installed?(:a_common_libs) %> };
      $('<%= maillogs.collect{ |maillog| "#change-#{maillog.notifiable.id}" }.uniq.join(', ') %>').each(function() {
        addJournalEmailLogLink.call(this, link_label, logs_path, options);
      });
      $('<%= maillogs.select{ |maillog| maillog.opened? }.collect{ |maillog| "#change-#{maillog.notifiable.id}" }.uniq.join(', ') %>').each(function() {
        $(this).find('a.icon-only.icon-email-log').addClass('opened');
      });
    <% end %>
  <% end %>
<% end %>

app/views/email_logs/_messages.html.erb
<% maillogs = @topic ? Maillog.where(:notifiable => @topic).to_a : [] %>
<% if maillogs.present? %>
  <%= javascript_tag do %>
    $('<a>', {
      title: '<%= escape_javascript(l(:label_email_log)) %>',
      'class': 'icon icon-email-log<%= ' opened' if maillogs.any?{ |maillog| maillog.opened? } %>',
      href: '<%= escape_javascript(raw(email_logs_path(:q => "redmine.message-#{@topic.id}."))) %>',
      text: '<%= escape_javascript(l(:label_email_log)) %>',
      click: function() {
        var $emailLog = $('#message-<%= @topic.id %>-email-log');
        if ($emailLog.length > 0) {
          $emailLog.toggle();
        } else {
          $.ajax({
            url: '<%= escape_javascript(raw(object_email_logs_path(:object_type => 'message', :object_id => @topic.id))) %>',
            success: function(data) {
              $('#content > div.message').first().before(data);
            }
          });
        }
        return false;
      }
    }).appendTo($('#content > .contextual').first());
  <% end %>
<% end %>

<% if @replies.present? %>
  <% maillogs = Maillog.where(:notifiable => @replies).to_a %>
  <% if maillogs.present? %>
    <%= javascript_tag do %>
      $('<%= maillogs.collect{ |maillog| "#message-#{maillog.notifiable.id}" }.uniq.join(', ') %>').each(function() {
        var $this = $(this);
        var $contextual = $this.find('.contextual');
        if ($contextual.length > 0) {
          var $target = $this.find('div.wiki');
          var messageId = $this.attr('id').substring(8);
          $('<a>', {
            title: '<%= escape_javascript(l(:label_email_log)) %>',
            'class': 'icon-only icon-email-log',
            href: '<%= escape_javascript(raw(email_logs_path)) %>?q=redmine.message-' + messageId + '.',
            text: '<%= escape_javascript(l(:label_email_log)) %>',
            click: function() {
              var $emailLog = $('#message-' + messageId + '-email-log');
              if ($emailLog.length > 0) {
                $emailLog.toggle();
              } else {
                $.ajax({
                  url: '<%= escape_javascript(raw(email_logs_path)) %>/message/' + messageId,
                  success: function(data) {
                    $target.before(data);
                  }
                });
              }
              return false;
            }
          }).appendTo($contextual.first()).before(' ');
        }
      });
      $('<%= maillogs.select{ |maillog| maillog.opened? }.collect{ |maillog| "#message-#{maillog.notifiable.id}" }.uniq.join(', ') %>').each(function() {
        $(this).find('a.icon-only.icon-email-log').addClass('opened');
      });
    <% end %>
  <% end %>
<% end %>

app/views/email_logs/index.html.erb
<h2><%= l(:label_email_logs) %></h2>

<%= form_tag({}, :method => :get) do %>
  <fieldset>
    <legend><%= l(:label_filter_plural) %></legend>
    <label for="from"><%= l(:label_date) %>:</label>
    <%= date_field_tag(:from, params[:from], :size => 10) %><%= calendar_for('from') %>
    <label for="to">-</label>
    <%= date_field_tag(:to, params[:to], :size => 10) %><%= calendar_for('to') %>
    <label for="q"><%= l(:label_search) %>:</label>
    <%= text_field_tag(:q, params[:q], :size => 40, :placeholder => l(:label_email_logs_search_placeholder)) %>
    <%= submit_tag(l(:button_apply), :class => 'small', :name => nil) %>
    <%= link_to(l(:button_clear), email_logs_path, :class => 'icon icon-reload') %>
  </fieldset>
<% end %>

<div class="autoscroll">
<table class="list email-logs odd-even">
  <thead>
    <tr>
      <th><%= l(:field_subject) %></th>
      <th><%= l(:label_recipients) %></th>
      <th><%= l(:label_date) %></th>
    </tr>
  </thead>
  <tbody>
    <% @maillogs.each do |maillog| %>
      <tr class="<%= cycle("odd", "even") %> collapsible collapsed">
        <td class="subject">
          <%= content_tag('span', maillog.attachments,
                          :title => l(:label_x_attachments, :count => maillog.attachments), :class => 'icon icon-attachment') if maillog.attachments > 0 %>
          <%= link_to_function('', "$(this).closest('tr').toggleClass('collapsed'); $(this).closest('tr').next().toggle();",
                               :title => l(:label_show_details), :class => 'icon-only email-details')
          %><span class="icon-only icon-email-log<%= ' opened' if maillog.opened? %>"></span>
          <%= render_subject(maillog) %>
        </td>
        <td class="recipients"><p><%= render_email_addresses(maillog.recipients) %></p></td>
        <td class="date"><%= format_time(maillog.date) %></td>
      </tr>
      <tr class="<%= current_cycle %>" style="display: none;">
        <td colspan="3" class="details">
          <div class="splitcontent">
            <div class="field-group splitcontentleft">
              <% maillog.addresses_by_fields.each do |field, addresses| %>
                <div class="field"><strong><%= l("label_field_#{field.downcase}") %>:</strong> <%= render_email_addresses(addresses, true) %></div>
              <% end %>
              <% if maillog.opened? %>
                <div class="field"><strong><%= l(:label_opened_at) %>:</strong> <%= format_time(maillog.opened_on) %></div>
              <% end %>
            </div>
            <div class="field-group splitcontentright">
              <% if maillog.project %>
                <div class="field"><strong><%= l(:label_project) %>:</strong> <%= link_to_project(maillog.project) %></div>
              <% end %>
              <% if maillog.notifiable_type.present? %>
                <div class="field"><strong><%= l(:label_field_notifiable) %>:</strong> <%= render_notifiable(maillog) %></div>
              <% end %>
              <div class="field"><strong><%= l(:label_field_message_id) %>:</strong> <%= maillog.message_id %></div>
            </div>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<span class="pagination"><%= pagination_links_full(@maillog_pages, @maillog_count) %></span>

<% html_title(l(:label_email_logs)) -%>

app/views/email_logs/show.html.erb
<div id="<%= @notifiable.class.name.demodulize.underscore %>-<%= @notifiable.id %>-email-log" class="splitcontent email-log">
  <div class="splitcontentleft">
    <div><strong><%= l(:label_sent_to) %>:</strong> <%= @recipients.collect{ |recipient| link_to_user(recipient) }.join(', ').html_safe %></div>
    <div><strong><%= l(:field_subject) %>:</strong> <%= h(@maillogs.first.subject) %></div>
  </div>
  <div class="splitcontentright">
    <div><strong><%= l(:label_sent_at) %>:</strong> <%= format_time(@maillogs.first.date) %></div>
    <div><strong><%= l(:label_field_message_id) %>:</strong> <%= render_maillog_links(@maillogs) %></div>
  </div>
</div>